#!/usr/bin/perl -w

use strict;
use ROBOTest;

#****x* SystemTest/header_size_test_pl
# FUNCTION
#   Test whether robodoc can handle large headers.  Robodoc uses a
#   dynamically expanding buffer for storing headers.  This dynamic
#   expansion might go wrong.  The input file for this test is
#   generated by the makefile entry header_size_test
# SOURCE
#

ROBOTest::start("Header Size Test");

#   They are 129 lines of the form
#      xxxxxxxxx_<number>
#   in the header.
#   Lets test if they all turn up in the documentation.
#
my $checksum = 0;
foreach my $n (1 .. 129) {
    $checksum += $n;
}
my $sum = 0;
while (my $line = <>) {
    if ($line =~ m/xxxx_(\d+)/) {
        $sum += $1;
    }
}

ROBOTest::assert( $sum == $checksum );
ROBOTest::finish;

0;

#*****

